version: '3.8'

services:
  service-a:
    build: ./service-a
    container_name: service-a
    ports:
      - "8080:8080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - SERVICE_B_URL=http://service-b:8081
    depends_on:
      - service-b
      - otel-collector
    networks:
      - app-network

  service-b:
    build: ./service-b
    container_name: service-b
    ports:
      - "8081:8081"
    env_file:
      - .env # Carrega a variável WEATHER_API_KEY do arquivo .env
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
    depends_on:
      - otel-collector
    networks:
      - app-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.102.1
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
    depends_on:
      - zipkin
    networks:
      - app-network

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge